### PR TITLE
Translations and i18n

### PR DESCRIPTION
**Pull request by Demmonius**
Hello everyone!

I love this theme, it's just one of the best I've seen.
This PR adds i18n management and translations.

How does it work?

1. List your languages in **config.yaml**:
```yaml
languages:
  fr:
    languageName: Français
    weight: 1

  en:
    languageName: English
    weight: 2
```

2. Create a directory per language just like:
```
data
├── en
│   ├── home.yaml
│   └── sections
│       ├── about.yaml
│       ├── achievements.yaml
│       ├── experiences.yaml
│       ├── projects.yaml
│       ├── recent-posts.yaml
│       └── skills.yaml
└── fr
    ├── home.yaml
    └── sections
        ├── about.yaml
        ├── achievements.yaml
        ├── experiences.yaml
        ├── projects.yaml
        ├── recent-posts.yaml
        └── skills.yaml

```

> By this way, you can add as much language as you want.

3. Switch the language in the header:
image

4. More information
Every _static_ content should be translate in **i18n/"language".toml** and use **{{i18n}} function** in the template. I started with some content but feel free to change it :D

### FOR THE QUOTES SUMMARY
I had to integrate it in a data section if we want to make it works with many languages, instead of **config.yaml**

@hossainemruz I need your help on the style, yep I'm terrible :(

IMPORTANT TO NOTICE: It doesn't break anything for old versions. We first try to translate but if it doesn't work, we try the old way.

### CODE REVIEW

**Comment by Demmonius** [comment]
Discussed in #38

**Comment by hossainemruz** [comment]
Hi @Demmonius!  really loved your hard work. I had no idea how to support translation. Thank you very much. Currently, I am reviewing it. I will try to update where necessary. I might need your help in case I don't understand something.

**Comment by p-vernaeckt** [comment]
Hi @hossainemruz ! Any idea on when this awesome PR will be merged? Oh and thank you @Demmonius !!

**Comment by hossainemruz** [comment]
There are few more thing to be done. I will try to as soon as possible. Just need some spare time.

**Comment by Demmonius** [comment]
Let me know if you need any help or explanations :)

**Comment by cristian04** [comment]
I’m also keen to help :)

**Comment by Demmonius** [comment]
> I’m also keen to help :)
> 
> Question: where should we put the post yaml files? My content has the language code as part of the file: post.md (english by default) post.es.md (Spanish)

Dokku manages translations in many ways... For the `data` section, we need to manage it by ourself (what I did in this PR). For the `posts`, dokku use the format you are talking. So it should still be working!

**Comment by Demmonius** [comment]
Maybe we should move the `customMenus` in the data section @hossainemruz ? Maybe some custom menus would need a translation

**Comment by hossainemruz** [comment]
Number of custom menus should not be more than one or two. I am not sure where we should move it. Perhaps, we can handle it through string translation 🤔.

**Comment by hossainemruz** [comment]
Sorry guys for my slow progress. Actually, I am not getting proper time to sit with this PR. I will merge this PR ASAP.

**Comment by hossainemruz** [comment]
@Demmonius I have moved the `customMenus` section and other translatable parameters into `site.yaml` files under data section.

**Comment by hossainemruz** [comment]
This PR still needs quite some works. I am going to complete them as soon as possible.

**TODOS:**
- [ ] Fix JS error during language change
- [ ] Use common static resources for all languages
- [ ] Handle post translation properly
- [ ] Fix responsiveness (language selector in mobile and tablet devices)

**Comment by p-vernaeckt** [comment]
Glad to know you're keeping up! I you need some help with testing, I can help ^^

**Comment by hossainemruz** [comment]
I think, finally this PR is ready. @Demmonius  and @p-vernaeckt  can you guys check this PR?

**Comment by p-vernaeckt** [comment]
Hi @hossainemruz !! Thanks a lot, I will check it asap, likely tomorrow.

**Comment by p-vernaeckt** [comment]
I've been switching to this PR and testing the result for an hour, so far so good. I approve the PR.

Oh and btw: good job @Demmonius !

**Comment by cristian04** [comment]
Take into consideration that the default navbar route for post entries was changed from `/posts/` to `/post`

`layouts/partials/navigators/navbar.html` line 56

**Comment by hossainemruz** [comment]
@cristian04 Thank you for noticing. Fixed in https://github.com/hossainemruz/toha/pull/91

**Pull request merged**
