### PR TITLE
Make soft skill's color configurable + add 'sky' and 'orange' colors

### PR DESCRIPTION
**Pull request by blueyetisoftware**

### CODE REVIEW

**Comment by hossainemruz** [comment]
For Sky Color, which one do you prefer?

First one is the current one with `#01e0fd` hexcode.
image
In the second one I have made it little darker with `#00c9e3` hexcode.
image

**Comment by ChapChap** [comment]
II think #2 is better looking `#00c9e3` among the other colors

**Comment by hossainemruz** [comment]
@ChapChap  What if we make this color code configurable? :thinking:  Instead of color name, he will provide color code. User can provide whatever color he want.

**Comment by ChapChap** [comment]
I think the best is to accept both options. The input is a string, if it is a color code, then the border-color is set to its value, else, seach its value among, predefined colors.
Most users (me included) struggle choosing the right color set... So for the convenience, its better to choose form predefined ones

**Comment by hossainemruz** [comment]
Ok. Sound good to me.

**Comment by hossainemruz** [comment]
@blueyetisoftware and @ChapChap I have made the colors configurable. Now, user can use either the pre-defined colors or he can provide his own color code. What do you think?

**Comment by blueyetisoftware** [comment]
Great changes. I have been modifying the theme for my personal use by overriding the css. Being able to set the colors from the yaml is a nice feature.

**Pull request merged**
