### PR TITLE
Allow section titles to be hidden inline

### PR DESCRIPTION
**Pull request by blueyetisoftware**

### CODE REVIEW

**Comment by blueyetisoftware** [comment]
@hossainemruz I wanted to be able to hide the title for certain sections. What is the best way to have them enabled by default so the user doesn't need to set `showTitle`?

**Comment by hossainemruz** [comment]
Can you please explain the use-case?

**Comment by blueyetisoftware** [comment]
I wanted to show some of the sections without title as they are somewhat obvious. For example, the projects section is pretty clear as is the achievements section at the bottom. The achievements section is very graphical and interactive. The title didn't always fit with the images. It was just a styling preference for some cases.

**Comment by hossainemruz** [comment]
Ok. Then, make showing title default behavior. Use `hideTitle`  instead of `showTitle`.

**Comment by blueyetisoftware** [comment]
I was trying to match up with `showOnNavbar`. I am running into something similar with title showing up in the footer. I would like to use `showOnNavbar`, `showOnSection` and `showOnFooter`. What do you think?

**Comment by hossainemruz** [comment]
>I would like to use `showOnNavbar`, `showOnSection` and `showOnFooter`.
I don't think we should add new variable for footer. If it was not shown on the navbar, then don't show in the footer too.

**Comment by blueyetisoftware** [comment]
I have updated the PR per the conversation above. Should be ready

**Comment by hossainemruz** [comment]
@blueyetisoftware Looks good so far. I will merge after some testing.

**Pull request merged**
