### PR TITLE
Allow section titles to be configured to match menu items

### PR DESCRIPTION
**Pull request by blueyetisoftware**

### CODE REVIEW

**Comment by blueyetisoftware** [comment]
Looks like you beat me to it with #14 . I like that PR much better

**Comment by blueyetisoftware** [comment]
I am reopening this one since I realized the names are not configurable on the section from #14 . This may need modification to be compatible with your other changes, but I am basically looking for a way to change the names and url for the different sections.

**Comment by hossainemruz** [comment]
Perhaps, you can do something like,
```yaml
section:
  name: Portfolio
  enable: true
  weight: 6
  showOnNavbar: true
  template: projects.html
```
Then, on the `index.html` page,
```html
{{ if .section.template }}
  {{- partial .section.template . -}}
{{ else }}
  {{- partial (printf "%s.html" (replace (lower .section.name) " " "-")) . -}}
{{ end }}
```

**Comment by blueyetisoftware** [comment]
PR replaced by #20

**Pull request closed without merging**
